version: '3.10'
services:
  django:
    build: ./airlines
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./airlines/:/usr/src/app
    ports:
      - 8000:8000

  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: 'session1_11'
    restart: always
    volumes:
      - ./db_django:/var/lib/mysql