# version: '3.10'
# services:
#   django:
#     build: ./airlines
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - ./airlines/:/usr/src/app
#     ports:
#       - 8000:8000

#   db:
#     image: mysql:5.7
#     ports:
#       - '3306:3306'
#     environment:
#       MYSQL_ALLOW_EMPTY_PASSWORD: true
#       MYSQL_DATABASE: 'session1_11'
#     restart: always
#     volumes:
#       - ./db_django:/var/lib/mysql

version: '3.10'
services:
  django:
    # Сборка образа для сервиса django из текущей директории
    build: .
    # Задание имени контейнера для сервиса django
    container_name: django
    # Задание команды, которую нужно запустить при запуске контейнера для сервиса django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    # Открытие порта на хостовой машине и перенаправление на порт в контейнере
    ports:
      - 8000:8000

  mysql:
    restart: always
    container_name: "mysql"
    image: mysql:latest
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: 'session1_11'