# Generated by Django 4.2.5 on 2023-11-10 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircrafts',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('MakeModel', models.CharField(max_length=10)),
                ('TotalSeats', models.IntegerField(max_length=11)),
                ('EconomySeats', models.IntegerField(max_length=11)),
                ('BusinessSeats', models.IntegerField(max_length=11)),
            ],
            options={
                'db_table': 'aircrafts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CountryID', models.IntegerField(max_length=11)),
                ('IATACode', models.CharField(max_length=3)),
                ('Name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'airports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'offices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Distance', models.IntegerField(max_length=11)),
                ('FlightTime', models.IntegerField(max_length=11)),
            ],
            options={
                'db_table': 'routes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('EconomyPrice', models.FloatField()),
                ('Confirmed', models.SmallIntegerField()),
                ('FlightNumber', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'schedules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=150, unique=True)),
                ('FirstName', models.CharField(max_length=50, null=True)),
                ('LastName', models.CharField(max_length=50)),
                ('Birthdate', models.DateField(null=True)),
                ('Active', models.SmallIntegerField(null=True)),
                ('OfficeID', models.ForeignKey(db_column='OfficeID', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.offices')),
                ('RoleID', models.ForeignKey(db_column='RoleID', default=0, on_delete=django.db.models.deletion.CASCADE, to='mainapp.roles')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AddedTables',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReportJuly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=10)),
                ('arrival', models.CharField(max_length=10)),
                ('age', models.CharField(default=0, max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('cabintype', models.CharField(max_length=30)),
                ('q1', models.IntegerField(default=0)),
                ('q2', models.IntegerField(default=0)),
                ('q3', models.IntegerField(default=0)),
                ('q4', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReportJune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=10)),
                ('arrival', models.CharField(max_length=10)),
                ('age', models.CharField(default=0, max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('cabintype', models.CharField(max_length=30)),
                ('q1', models.IntegerField(default=0)),
                ('q2', models.IntegerField(default=0)),
                ('q3', models.IntegerField(default=0)),
                ('q4', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReportMay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=10)),
                ('arrival', models.CharField(max_length=10)),
                ('age', models.CharField(default=0, max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('cabintype', models.CharField(max_length=30)),
                ('q1', models.IntegerField(default=0)),
                ('q2', models.IntegerField(default=0)),
                ('q3', models.IntegerField(default=0)),
                ('q4', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_start', models.DateTimeField()),
                ('last_confirmation', models.DateTimeField(null=True)),
                ('error_status', models.CharField(default='Lost connection.', max_length=50, null=True)),
                ('session_end', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=1, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
