# Generated by Django 4.2.5 on 2023-09-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_user_id_sessions_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='status',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
