# Generated by Django 4.2.5 on 2023-09-26 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0005_sessions_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Countries",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "countries",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Offices",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("Title", models.CharField(max_length=50)),
                ("Phone", models.CharField(max_length=50)),
                ("Contact", models.CharField(max_length=250)),
            ],
            options={
                "db_table": "offices",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Roles",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("Title", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "roles",
                "managed": False,
            },
        ),
        migrations.AlterField(
            model_name="users",
            name="OfficeID",
            field=models.ForeignKey(
                db_column="OfficeID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.offices",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="RoleID",
            field=models.ForeignKey(
                db_column="RoleID",
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.roles",
            ),
        ),
    ]
