# Generated by Django 4.2.5 on 2023-09-28 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_countries_offices_roles_alter_users_officeid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='OfficeID',
            field=models.ForeignKey(db_column='Office_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.offices'),
        ),
    ]
