# Generated by Django 4.2.5 on 2023-09-29 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_users_officeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='OfficeID',
            field=models.ForeignKey(db_column='OfficeID', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.offices'),
        ),
        migrations.AlterField(
            model_name='users',
            name='RoleID',
            field=models.ForeignKey(db_column='RoleID', default=0, on_delete=django.db.models.deletion.CASCADE, to='mainapp.roles'),
        ),
    ]
