# Generated by Django 4.2.5 on 2023-10-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0009_alter_users_officeid_alter_users_roleid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessions",
            name="last_confirmation",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="sessions",
            name="session_end",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="sessions",
            name="session_start",
            field=models.DateTimeField(),
        ),
    ]
