# Generated by Django 4.2.5 on 2023-10-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_sessions_last_confirmation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircrafts',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('MakeModel', models.CharField(max_length=10)),
                ('TotalSeats', models.IntegerField(max_length=11)),
                ('EconomySeats', models.IntegerField(max_length=11)),
                ('BusinessSeats', models.IntegerField(max_length=11)),
            ],
            options={
                'db_table': 'aircrafts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CountryID', models.IntegerField(max_length=11)),
                ('IATACode', models.CharField(max_length=3)),
                ('Name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'airports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Distance', models.IntegerField(max_length=11)),
                ('FlightTime', models.IntegerField(max_length=11)),
            ],
            options={
                'db_table': 'routes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('EconomyPrice', models.FloatField()),
                ('Confirmed', models.SmallIntegerField()),
                ('FlightNumber', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'schedules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AddedTables',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=500)),
            ],
        ),
    ]
