# Generated by Django 4.2.5 on 2023-10-23 13:16

from django.db import migrations, models

from mainapp.models import *
import csv
import os
from django.conf import settings

def fill_database_may(apps, schema_editor):
    base_dir = settings.BASE_DIR
    csv_file = os.path.join(base_dir, 'csv_files/survey_05.csv')

    with open(csv_file, 'r') as file:
        csv_reader = csv.DictReader(file)
        for row in csv_reader:
            ReportMay.objects.create(
                departure = row['Departure'],
                arrival = row['Arrival'],
                age =  row['Age'],
                gender = row['Gender'],
                cabintype = row['CabinType'],
                q1 = row['Q1'],
                q2 = row['Q2'],
                q3 = row['Q3'],
                q4 = row['Q4']
            )

def fill_database_june(apps, schema_editor):
        base_dir = settings.BASE_DIR
        csv_file = os.path.join(base_dir, 'csv_files/survey_06.csv')

        with open(csv_file, 'r') as file:
            csv_reader = csv.DictReader(file)
            for row in csv_reader:
                ReportJune.objects.create(
                    departure = row['Departure'],
                    arrival = row['Arrival'],
                    age =  row['Age'],
                    gender = row['Gender'],
                    cabintype = row['CabinType'],
                    q1 = row['Q1'],
                    q2 = row['Q2'],
                    q3 = row['Q3'],
                    q4 = row['Q4']
                )

def fill_database_july(apps, schema_editor):
        base_dir = settings.BASE_DIR
        csv_file = os.path.join(base_dir, 'csv_files/survey_07.csv')

        with open(csv_file, 'r') as file:
            csv_reader = csv.DictReader(file)
            for row in csv_reader:
                ReportJuly.objects.create(
                    departure = row['Departure'],
                    arrival = row['Arrival'],
                    age =  row['Age'],
                    gender = row['Gender'],
                    cabintype = row['CabinType'],
                    q1 = row['Q1'],
                    q2 = row['Q2'],
                    q3 = row['Q3'],
                    q4 = row['Q4']
                )

class Migration(migrations.Migration):
    
    dependencies = [
        ("mainapp", "0012_files"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportJuly",
            fields=[
                (
                    "id", 
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure", models.CharField(max_length=10)),
                ("arrival", models.CharField(max_length=10)),
                ("age", models.CharField(default=0, max_length=30)),
                ("gender", models.CharField(max_length=10)),
                ("cabintype", models.CharField(max_length=30)),
                ("q1", models.IntegerField(default=0)),
                ("q2", models.IntegerField(default=0)),
                ("q3", models.IntegerField(default=0)),
                ("q4", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ReportJune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure", models.CharField(max_length=10)),
                ("arrival", models.CharField(max_length=10)),
                ("age", models.CharField(default=0, max_length=30)),
                ("gender", models.CharField(max_length=10)),
                ("cabintype", models.CharField(max_length=30)),
                ("q1", models.IntegerField(default=0)),
                ("q2", models.IntegerField(default=0)),
                ("q3", models.IntegerField(default=0)),
                ("q4", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ReportMay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure", models.CharField(max_length=10)),
                ("arrival", models.CharField(max_length=10)),
                ("age", models.CharField(default=0, max_length=30)),
                ("gender", models.CharField(max_length=10)),
                ("cabintype", models.CharField(max_length=30)),
                ("q1", models.IntegerField(default=0)),
                ("q2", models.IntegerField(default=0)),
                ("q3", models.IntegerField(default=0)),
                ("q4", models.IntegerField(default=0)),
            ],
        ),


        migrations.RunPython(fill_database_may),
        migrations.RunPython(fill_database_june),
        migrations.RunPython(fill_database_july),
    ]
